#!/usr/bin/env bash
# using ideas from https://github.com/punchagan/ansible-system-setup/blob/main/bootstrap to set up mine

set -euo pipefail

URL="https://github.com/dabrown645/laptop.git"

# Install Ansible (ansible-pull and Git
if $(type -P apt > /dev/null) ; then
    (which ansible-pull && which git) || (sudo apt update && sudo apt install -y ansible git)
elif $(type -P pacman > /dev/null) ; then
    (which ansible-pull && which git) || (sudo pacman -Syu ansible git)
elif $(type -P zypper >/dev/null); then
    (which ansible-pull && which git) || (sudo zypper install -y ansible git)
else
    echo "OS type not supported"
fi

# Create ansible log directory
# NOTE: Ensure it i the same as in the log path in Ansible.cfg
mkdir -p /var/log

if  [[ ${#} -ge 1 ]] ; then
    branch=${1:-main}
    shift
fi

ansible-pull --url ${URL} --ask-become-pass --checkout ${branch} ${@}
