---
# tasks to completed before running roles
- hosts: all
  tags: always
  become: true

  pre_tasks:
    - name: Show ansible family and ansible_distribution
      debug:
        msg:
          - "Family {{ ansible_os_family }} Distribution {{ ansible_distribution }}"
          - "archlinux_oses = {{ archlinux_oses }}"
          - "debian_oses = {{ debian_oses }}"
        verbosity: 1

    - name: "pre-run | update system before starting package cache (arch)"
      pacman: 
        update_cache: yes
        upgrade: yes
      changed_when: false
      when: ansible_distribution in archlinux_oses

    - name: "pre-run } update package cache (debian, etc)"
      apt: 
        update_cache: yes
        upgrade: full
        state: latest
      changed_when: false
      when: ansible_distribution in debian_oses
        
  roles:
    - base
    
## run roles
#- hosts: workstation
#  tags: workstation
#  become: true
#  roles:
#    - workstation