# tasks to completed before running roles
- hosts: all
  tags: always
  become: true
  pre_tasks:
    - name: "pre-run | update package cache (arch)"
      tags: always
      pacman: update_cache=yes
      change_when: false
      when: ansible_distribution == "Archlinux"
    - name: "pre-run } update package cache (debian, etc)"
      tages: always
      apt: update_cache=yes
      change_when: false
      when: ansible_distribution in ["Debian", "Ubuntu"]