---
- name: setup user ansible
  tags: ansible
  block:
    - name: users | create group
      tags: groups
      group:
        name: ansible
        state: present

    - name: users | setup sudo
      tags: sudo
      block:
        - name: users | create users
          user:
            name: ansible
            group: ansible
            groups: "{{ item }}"
            state: present
            comment: "David A Brown - Ansible"
            shell: /bin/nologin
            system: yes
            home: /var/lib/ansible
          environment:
            umask: 027
          loop:
              - ansible
              - "{{ sudo_group }}"

        - name: users | add sudoers file
          copy:
            src: users/sudoers_ansible
            dest: /etc/sudoers.d/ansible
            owner: root
            group: root
            mode: 0440

    - name: users | add to adm grp if exists
      tags: adm
      user:
        name: ansible
        groups: "{{ adm_group }}"
      when: adm_group is defined
