---
- name: setup user dabrown
  tags: dabrown
  block:
    - name: users | create group
      tags: groups
      group:
        name: dabrown
        gid: 2000
        state: present

    - name: users | setup sudo
      tags: sudo
      block:
        - name: users | create users
          user:
            name: dabrown
            uid: 2000
            group: dabrown
            groups: "{{ item }}"
            state: present
            comment: "David A Brown"
            shell: /bin/bash
          environment:
            umask: 027
          loop:
              - ansible
              - "{{ sudo_group }}"

        - name: users | add sudoers file
          copy:
            src: users/sudoers_dabrown
            dest: /etc/sudoers.d/dabrown
            owner: root
            group: root
            mode: 0440

    - name: users | add to adm grp if exists
      tags: adm
      user:
        name: dabrown
        groups: "{{ adm_group }}"
      when: adm_group is defined
