---
- name: audacity
  tags: audacity
  block:
    - name: software | audacity | install
      package:
        name:
          - audacity
        state: present
      when: audacity|bool

    - name: software | audacity | remove
      package:
        name:
          - audacity
        state: absent
      when: not audacity|bool
