---
- name: audacious
  tags: audacious
  block:
    - name: software | audacious | install
      package:
        name:
          - audacious
          - audacious-plugins
        state: present
      when: audacious|bool

    - name: software | audacious | remove
      package:
        name:
          - audacious
          - audacious-plugins
        state: absent
      when: not audacious|bool
