---
- name: bitwarden
  tags: bitwarden
  block:
    - name: software | bitwarden | install
      flatpak:
        name: com.bitwarden.desktop
        state: present
      when: bitwarden|bool

    - name: software | bitwarden | remove
      flatpak:
        name: com.bitwarden.desktop
        state: absent
      when: not bitwarden|bool