---
- name: software | bitwarden | install
  tags: bitwarden, install
  flatpak:
    name: com.bitwarden.desktop
    state: present
  when: bitwarden

- name: software | bitwarden | remove
  tags: bitwarden,remove
  flatpak:
    name: com.bitwarden.desktop
    state: present
  when: not bitwarden