---
- name: brave
  tags: brave
  block:
    - name: software | brave | install
      package:
        name: "{{ item }}"
        state: present
      loop:
       - "{{ brave_packages }}"
      when: brave|bool

    - name: software | brave | remove
      package:
        name: "{{ item }}"
        state: absent
      loop:
       - "{{ brave_packages }}"
      when: not brave|bool
