---
- name: caffeine
  tags: caffeine
  block:
    - name: software | caffeine | install
      package:
        name:
          - caffeine
        state: present
      when: caffeine|bool

    - name: software | caffeine | remove
      package:
        name:
          - caffeine
        state: absent
      when: not caffeine|bool
