---
- name: calibre
  tags: calibre
  vars: 
    pkg_name: com.calibre_ebook.calibre
  block:
    - name: software | calibre | install
      flatpak:
        name: "{{ pkg_name }}"
        state: present
      when: calibre|bool

    - name: software | calibre | remove
      flatpak:
        name: "{{ pkg_name }}"
        state: absent
      when: not calibre|bool