---
- name: calibre
  tags: calibre
  block:
    - name: software | calibre | install
      package:
        name: "{{ item }}"
        state: present
      loop:
        - "{{ calibre_packages }}"
      when: calibre|bool

    - name: software | calibre | remove
      package:
        name: "{{ item }}"
        state: absent
      loop:
        - "{{ calibre_packages }}"
      when: not calibre|bool