---
- name: chromium
  tags: chromium
  block:
    - name: software | chromium | install
      package:
        name:
          - chromium
        state: present
      when: chromium|bool

    - name: software | chromium | remove
      package:
        name:
          - chromium
        state: absent
      when: not chromium|bool
