---
- name: chromium
  tags: chromium
  block:
    - name: software | chromium | install
      package:
        name: "{{ item }}"
        state: present
      loop:
        - "{{ chromium_packages }}"
      when: chromium|bool

    - name: software | chromium | remove
      package:
        name: "{{ item }}"
        state: absent
      loop:
        - "{{ chromium_packages }}"
      when: not chromium|bool
