---
- name: codecs
  tags: codecs
  block:
    - name: software | codecs | install
      package:
        name: "{{ item }}"
        state: present
      loop:
        - "{{ gstreamer_packages }}"
      when: codecs|bool

    - name: software | codecs | remove
      package:
        name: "{{ item }}"
        state: present
      loop:
        - "{{ gstreamer_packages }}"
      when: not codecs|bool
