---
- name: codecs
  tags: codecs
  block:
    - name: software | codecs | install
      package:
        name:
          - "{{ gstreamer_libav_package }}"
          - "{{ gstreamer_plugins_bad_package }}"
        state: present
      when: codecs|bool

    - name: software | codecs | remove
      package:
        name:
          - "{{ gstreamer_libav_package }}"
          - "{{ gstreamer_plugins_bad_package }}"
        state: present
      when: not codecs|bool
