---
- name: darktable
  tags: darktable
  block:
    - name: software | darktable | install
      package:
        name:
          - darktable
        state: present
      when: darktable|bool

    - name: software | darktable | remove
      package:
        name:
          - darktable
        state: absent
      when: not darktable|bool
