---
- name: software | darktable | install
  #tags: packages,darktable,install
  package:
    name:
      - darktable
    state: present
  when: darktable

- name: software | darktable | remove
  tags: packages,darktable,remove
  package:
    name:
      - darktable
    state: absent
  when: not darktable
