---
- name: google_chrome
  tags: google_chrome
  block:
    - name: software | google_chrome | install
      package:
        name: "{{ item }}"
        state: present
      loop:
        - "{{ google_chrome_packages }}"
      when: google_chrome|bool

    - name: software | google_chrome | remove
      package:
        name: "{{ item }}"
        state: absent
      loop:
        - "{{ google_chrome_packages }}"
      when: not google_chrome|bool