---
- name: inkscape
  tags: inkscape
  block:
    - name: software | inkscape | install
      tags: packages,inkscape,install
      package:
        name:
          - "{{ inkscape_package }}"
        state: present
      when: inkscape|bool

    - name: software | inkscape | remove
      tags: packages,inkscape,remove
      package:
        name:
          - "{{ inkscape_package }}"
        state: absent
      when: not inkscape|bool
