---
- name: software | kdevlive | install
  package:
    name:
      - kdenlive
      - kdenlive-data
      - kdenlive-dbg
    state: present
  when:
  - kdenlive

- name: software | kdevlive | remove
  package:
    name:
      - kdenlive
      - kdenlive-data
      - kdenlive-dbg
    state: absent
  when:
  - not kdenlive