---
- name: kdenlive
  tags: kdenlive
  block:
    - name: software | kdenlive | install
      package:
        name:
          - kdenlive
          - kdenlive-data
          - kdenlive-dbg
        state: present
      when:
      - kdenlive|bool

    - name: software | kdenlive | remove
      package:
        name:
          - kdenlive
          - kdenlive-data
          - kdenlive-dbg
        state: absent
      when:
      - not kdenlive|bool
