---
- name: kdenlive
  tags: kdenlive
  block:
    - name: software | kdenlive | install
      package:
        name: "{{ item }}"
        state: present
      loop:
        - "{{ kdenlive_packages }}"
      when:
      - kdenlive|bool

    - name: software | kdenlive | remove
      package:
        name: "{{ item }}"
        state: absent
      loop:
        - "{{ kdenlive_packages }}"
      when:
      - not kdenlive|bool
