---
- name: libreoffice
  tags: libreoffice
  block:
    - name: software | libreoffice | install
      package:
        name: libreoffice
        state: present
      when:
        - libreoffice|bool

    - name: software | libreoffice | removal
      package:
        name: libreoffice
        state: absent
      when:
        - not libreoffice|bool
