---
- name: libreoffice
  tags: libreoffice
  block:
    - name: software | libreoffice | install
      package:
        name: "{{ item }}"
        state: present
      loop:
        - "{{ libreoffice_packages }}"
      when:
        - libreoffice|bool

    - name: software | libreoffice | removal
      package:
        name: "{{ item }}"
        state: absent
      loop:
        - "{{ libreoffice_packages }}"
      when:
        - not libreoffice|bool
