---
# As of 2020-06-18 lutris is not available on Debian
- name: software | lutris
  block:
    - name: software | lutris | install
      block:
        - name: software | lutris | add repo
          apt_repository:
            repo: 'ppa:lutris-team/lutris'
            state: present
  
        - name: softwar | lutris | install
          package:
            name: lutris
            state: present
      when:
        - lutris

    - name: software | lutris | remove
      block:
        - name: software | lutris | remove repo
          apt_repository:
            repo: 'ppa:lutris-team/jutris'
            state: absent
  
        - name: softwar | lutris | remov3
          package:
            name: 
              - lutris
              - winetricks
            state: absent
      when:
        - not lutris
  when:
    ansible_distribution in ["Pop!_OS", "Ubuntu"]
  
