---
- name: games
  tags: games
  vars:
    pkg_names:
      - chromium-bsu
      - extremetuxracer
      - frozen-bubble
      - gnome-chess
      - kmines
      - "{{ nethack_package }}"
      - supertux
      - supertuxkart
      - wesnoth
  block:
    - name: software | games | install
      package:
        name: "{{ pkg_names }}"
        state: present
      when: games|bool

    - name: software | games | remove
      package:
        name: "{{ pkg_names }}"
        state: absent
      when: not games|bool
