---
- name: software | games | install
  package:
    name:
      - chromium-bsu
      - extremetuxracer
      - frozen-bubble
      - gnome-chess
      - "{{ nethack_package }}"
      - supertux
      - supertuxkart
      - wesnoth
    state: present
  when: games

- name: software | games | remove
  package:
    name:
      - chromium-bsu
      - extremetuxracer
      - frozen-bubble
      - gnome-chess
      - "{{ nethack_package }}"
      - supertux
      - supertuxkart
      - wesnoth
    state: absent
  when: not games