---
- name: misc packages
  tags: misc_packages
  block:
    - name: software | workstation distribution packages install
      package:
        name: "{{ item }}"
        state: present
      loop:
        - acpid
        - alsa-utils
        - "{{ bzip2_package }}"
        - "{{ cups_package }}"
        - "{{ cryptsetup_package }}"
        - dconf-editor
        - dialog
        - "{{ font_fira_mono_package }}"
        - "{{ font_noto_emoji_package }}"
        - gparted
        - "{{ hunspell_package }}"
        - "{{ hyphen_package }}"
        - "{{ network_manager_openvpn_package }}"
        - "{{ network_manager_package }}"
        - "{{ network_manager_pptp_package }}"
        - neovim
        - "{{ p7zip_package }}"
        - pavucontrol
        - unrar
        - "{{ wireless_tools_package }}"
        - "{{ wpa_supplicant_package }}"
      when: misc_packages|bool

    - name: software | workstation distribution packages remove
      package:
        name: "{{ item }}"
        state: absent
      loop:
        - acpid
        - alsa-utils
        - "{{ bzip2_package }}"
        - "{{ cups_package }}"
        - "{{ cryptsetup_package }}"
        - dconf-editor
        - dialog
        - "{{ font_fira_mono_package }}"
        - "{{ font_noto_emoji_package }}"
        - gparted
        - "{{ hunspell_package }}"
        - "{{ hyphen_package }}"
        - "{{ network_manager_openvpn_package }}"
        - "{{ network_manager_package }}"
        - "{{ network_manager_pptp_package }}"
        - neovim
        - "{{ p7zip_package }}"
        - pavucontrol
        - unrar
        - "{{ wireless_tools_package }}"
        - "{{ wpa_supplicant_package }}"
      when: not misc_packages|bool
