---
- name: openshot
  tags: openshot
  block:
    - name: software | openshot | install
      package:
        name: "{{ openshot_packages }}"
        state: present
      loop:
        - "{{ openshot_packages }}"
      when:
        - openshot|bool

    - name: software | openshot | remove
      package:
        name: "{{ openshot_packages }}"
        state: absent
      loop:
        - "{{ openshot_packages }}"
      when:
        - not openshot|bool
