---
- name: thunderbird
  tags: thunderbird
  block:
    - name: software | thunderbird | install
      package:
        name: thunderbird
        state: present
      when:
        - thunderbird|bool

    - name: software | thunderbird | remove
      package:
        name: thunderbird
        state: absent
      when:
        - not thunderbird|bool
