---
- name: virtualbox
  tags: virtualbox
  block:
    - name: software | virtualbox | install
      package:
        name: "{{ item }}"
        state: present
      loop:
        - "{{ virtualbox_packages }}"
      when:
        - virtualbox|bool

    - name: software | virtualbox | remove
      package:
        name: "{{ item }}"
        state: absent
      loop:
        - "{{ virtualbox_packages }}"
      when:
        - not virtualbox|bool