---
- name: utilities
  tags:
    - settings
    - system
    - utilities
  block:
    - name: system setup | utilities | install utility packages
      tags:
        - system
        - settings
      package:
        name: "{{ item }}"
        state: present
      loop:
        - at
        - colordiff
        - curl
        - "{{ dns_utils_package }}"
        - htop
        - iotop
        - "{{ lm_sensors_package }}"
        - lsof
        - ncdu
        - neofetch
        - net-tools
        - "{{ nfs_client_package }}"
        - nmap
        - ranger
        - "{{ rename_package }}"
        - rsync
        - screen
        - sshfs
        - tmux
        - traceroute
        - "{{ vim_package }}"
        - wget
        - whois

    - name: system setup | utilities | install man-pages (arch)
      tags:
        - system
        - settings
        - manpage
      pacman:
        state: present
        name:
          - man-db
          - man-pages
      when: ansible_distribution == "Archlinux"
