---
- name: system setup | development packages | install packages
  tags:
    - dev
    - python
  package:
    name: "{{ item }}"
    state: present
  loop:
    - "{{ editor_packages }}"
    - "{{ development_packages }}"

