---
- name: system setup | development packages | install packages
  tags: 
    - dev
    - python
  package:
    name:
      - fabric
      - flake8
      - git
      - perl
      - "{{ python_flake8_package }}"
      - "{{ python_package }}"
      - "{{ python_pip_package }}"
      - "{{ python_pyflakes_package }}"
      - python-setuptools
      - "{{ python_virtualenv_package }}"
    state: present