---
- name: system setup | pip packages | install
  tags:
    - pip
    - python
  become: true
  become_user: "{{ main_user }}"
  pip:
    executable: /usr/bin/pip3
    state: present
    name: "{{ item }}"
    loop:
      - bpytop