---
- name: Arch repository settings/packages
  tags: archsettngs
  block:
    - name: system setup | repositories | add ignored packages for archlinux hosts
      lineinfile:
        dest: /etc/pacman.conf
        regexp: "^#IgnorePkg"
        line: "IgnorePkg = ansible linux linux linux-headers linux-lts linux-lts-headers"
        
    - name: system_setup | repositories | install package management tools
      package:
        name:
          - pacman    # default package manager
          - pamac     # wrapper around pacman more like apt
          - pamac-aur # AUR helper for pamac
          - pamac-all # everything all in one
          - aura      # AUR helper
          - paru      # AUR helper
  when: ansible_distribution == "Archlinux"

- name: Debian/Ubuntu repository settings/packages
  tags: debsettings
  block:
    - name: system setup | repositories | install package management tools (debian-based)
      tags:
        - system
        - settings
      package:
        name:
          - aptitude
          - software-properties-common
        state: present
  when: ansible_distribution in debian_oses
