---
- name: Arch repository settings/packages
  tags: archsettngs
  block:
    - name: system setup | repositories | add ignored packages for archlinux hosts
      lineinfile:
        dest: /etc/pacman.conf
        regexp: "^#IgnorePkg"
        line: "IgnorePkg = ansible linux linux linux-headers linux-lts linux-lts-headers"
    
    #- name: system setup | flatpak
    #  package: flatpak
    #  state: present
    #  when: flatpak|bool
    
    #- name: system setup | snapd
    #  package: snapd
    #  state: present
    #  when: snap|bool
   # 
    - name: system setup | appimage
      package:
        name:
          - libappimage
          - appimagelauncher
        state: present
      when: appimage|bool
        
    - name: system_setup | repositories | install package management tools
      pacman:
        name:
          - pacman    # default package manager
          - archlinux-appstream-data-pamac
          - aura      # AUR helper
          - paru      # AUR helper
          - octopi
          - bauh
          #- pamac-all
        state: present
      
    #- name: system_setup | install ansible aur module
    #  community.general.ansible_galaxy_install:
    #    type: collection
    #    name: kewlfft.aur
    
    #- name: system_setup | create ansible module dir
    #  file:
    #    path: ~/.ansible/plugins/modules
    #    state: directory
    #    
    #- name: system_setup | download ansible module aur
    #  get_url:
    #    url: https://raw.githubusercontent.com/kewlfft/ansible-aur/master/plugins/modules/aur.py
    #    dest: ~/.ansible/plugins/modules

    #- name: system_setup | pamac-all
    #  aur:
    #    name: pamac-all
    #    use: auto
    #    state: present
    #  become_user: ansible
    #  become: yes

  when: ansible_distribution == "Archlinux"

- name: Debian/Ubuntu repository settings/packages
  tags: debsettings
  block:
    - name: system setup | repositories | install package management tools (debian-based)
      tags:
        - system
        - settings
      package:
        name:
          - aptitude
          - software-properties-common
        state: present
  when: ansible_distribution in debian_oses
