---
- name: base role
  tags: base
  block:
    - name: Load distro-specific variables
      tags: always
      include_vars: "{{ ansible_distribution }}.yml"

    - name: Set up the ansible environment
      tags:
        - ansible_setup
      import_tasks: ansible_setup.yml

    - name: Verify users exist
      tags: users
      block:
    #    - import_tasks: users/ansible.yml
        - import_tasks: users/dabrown.yml

    - name: Install base software
      tags: packages
      block:
        - import_tasks: software/repositories.yml
        - import_tasks: software/packages_cleanup.yml
        #- import_tasks: software/packages_development.yml
        #- import_tasks: software/packages_pip.yml
        #- import_tasks: software/packages_utilities.yml

    - name: Perform system configutations
      tags:
       - system
      block:
        - import_tasks: system_setup/clock.yml
        - import_tasks: system_setup/cron.yml
        - import_tasks: system_setup/locale.yml
        - import_tasks: system_setup/logging.yml
        - import_tasks: system_setup/memory.yml
        - import_tasks: system_setup/microcode.yml
        - import_tasks: system_setup/openssh.yml
        - import_tasks: system_setup/scripts.yml
  become: true
