- name: system setup | memory | adjust current swappiness
  tags: swappiness,systemctl,system,setup
  lineinfile:
    dest: "/etc/sysctl.conf"
    create: yes
    regexp: "swappiness ="
    line: "vm.swappiness = 5"
  register: swappiness

- name: system setup | memory | apply swappiness
  tags: swappiness,sysctl,system,setup
  command: sysctl vm.swappiness={{ swappiness_value }}
  when: swappiness.changed