---
- name: memory
  tags:
    - memory
    - setup
    - swappiness
    - system
    - systemctl
  block:
    - name: system setup | memory | adjust current swappiness
      lineinfile:
        dest: "/etc/sysctl.conf"
        create: yes
        regexp: "swappiness ="
        line: "vm.swappiness = 5"
      register: swappiness

    - name: system setup | memory | apply swappiness
      command: sysctl vm.swappiness={{ swappiness_value }}
      when: swappiness.changed
