---
- name: microcode
  tags:
    - cpu
    - microcode
    - setup
    - system
  block:
    - name: system setup | microcode | install package for amd
      tags: amd
      package:
        name: "{{ amd_microcode_package }}"
        state: present
      when:
        - microcode_amd_install|bool

    - name: system setup | microcode | install package for intel
      tags: intel
      package:
        name: "{{ intel_microcode_package }}"
        state: present
      when:
        - microcode_intel_install|bool
