---
- name: openssh
  tags:
    - openssh
    - setup
    - ssh
    - system
  vars:
    pkg_names:
      - "{{ openssh_package }}"
      - openssh-client
      - openssh-sftp-server
  block:
    - name: system setup | openssh | install or update daemon package
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - pkg_names

    - name: system setup | openssh | generate sshd_config file from template
      template:
        src: sshd_config.j2
        dest: /etc/ssh/sshd_config
        owner: root
        group: root
        mode: 0644

    - name: system setup | openssh | copy issue.net
      copy:
        src: system_setup/openssh_issue.net
        dest: /etc/issue.net
        owner: root
        group: root
        mode: 0644

    - name: system setup | openssh | enable daemon
      service:
        name: "{{ openssh_service }}"
        enabled: true
        state: started
