---
- name: openssh
  tags:
    - openssh
    - setup
    - ssh
    - system
  block:
    - name: system setup | openssh | install or update daemon package
      package:
        name: "{{ openssh_package }}"
        state: present
      notify: restart_sshd

    - name: system setup | openssh | enable daemon
      service:
        name: "{{ openssh_service }}"
        enabled: true
        state: started

    - name: system setup | openssh | generate sshd_config file from template
      template:
        src: sshd_config.j2
        dest: /etc/ssh/sshd_config
        owner: root
        group: root
        mode: 0644
      notify: restart_sshd

    - name: system setup | openssh | copy issue.net
      copy:
        src: system_setup/openssh_issue.net
        dest: /etc/issue.net
        owner: root
        group: root
        mode: 0644
